name: Update BTC Data Hourly

on:
  schedule:
    # Run every hour at minute 5 (e.g., 1:05, 2:05, etc.)
    - cron: '5 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests pytz
      
      - name: Update BTC OHLC Data
        run: python update_data.py
      
      - name: Generate Report
        run: python generate_report.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff --staged --quiet || git commit -m "📊 Auto-update BTC data - $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
